### ISSUE TITLE
OS name sometimes does not fit in specs tab

### ISSUE THREAD

**Issue by micwoj92** [rcmaehl/NotCPUCores#100]
![image](https://user-images.githubusercontent.com/45581170/107916680-f7393180-6f66-11eb-8f02-9f74dab4a14a.png)

Minor visual bug, I've checked [Microsoft Windows versions](https://en.wikipedia.org/wiki/List_of_Microsoft_Windows_versions) and it seems that some other longer names like "Windows 10 Enterprise LTSC" could also be affected by this.

**Comment by micwoj92** [comment]
![image](https://user-images.githubusercontent.com/45581170/108038175-d3dfb680-703a-11eb-899f-b0f57f4177be.png)

Fixed, before closing I will also try with "Windows 10 Pro for Workstations" because it seems to be longest.

**Comment by micwoj92** [comment]
![image](https://user-images.githubusercontent.com/45581170/108135066-b7ce2a80-70b7-11eb-8c1b-3e8a5b80f2a2.png)

Microsoft wins again!

**Comment by rcmaehl** [comment]
> ![image](https://user-images.githubusercontent.com/45581170/108135066-b7ce2a80-70b7-11eb-8c1b-3e8a5b80f2a2.png)
> 
> Microsoft wins again!

AAAAAAAAAAAAAAAAAAA

**Comment by micwoj92** [comment]
I think whole tab needs to be wider lol 
![Uploading image.png…]()

**Comment by micwoj92** [comment]
![image](https://user-images.githubusercontent.com/45581170/108141877-e1da1980-70c4-11eb-9442-f1f77d490b50.png)
Shows correctly now and this is the longest Windows name I am aware of. Step up your game Microsoft!

**Comment by micwoj92** [comment]
![image](https://user-images.githubusercontent.com/45581170/109375326-2a12ec00-78bc-11eb-8eb6-d95147866394.png)

Reopen, broken on Windows Server :weary: 
![image](https://user-images.githubusercontent.com/45581170/109375333-3c8d2580-78bc-11eb-8fac-d95ae855635d.png)

**Comment by micwoj92** [comment]
![image](https://user-images.githubusercontent.com/45581170/109375547-e9b46d80-78bd-11eb-8cf4-bfc6624bc340.png)
This is the longest I could find ~as of now~
Windows Server 2016 Datacenter Evaluation 64-bit

**Comment by micwoj92** [comment]
The probability of someone using NotCpuCores with that version of Windows is literally 0, I found some possible longer names but was not able to find iso files.
