### ISSUE TITLE
Request: include Childprocesses

### ISSUE THREAD

**Issue by Benman2785** [rcmaehl/NotCPUCores#109]
Hey,

would be great if childprocesses get also set affinity

have in mind: you need to add the priority "auto" as manual setting a different prio can cause sync-errors in game.

this is actually needed right now - as games like Cyberpunk and Metro Exodus or Hunt start childs that are crucial for a "lag-free" gameplay ;)

**Comment by micwoj92** [comment]
I think this is duplicate of #9

**Comment by rcmaehl** [comment]
Unfortunately it is.
