### ISSUE TITLE
german translation

### ISSUE THREAD

**Issue by Benman2785** [rcmaehl/NotCPUCores#111]
hey, i had some time to kill - here is a german translation ;)

very old ;)
EDIT: for latest version scroll down!

i hope everything was set correctly ;)

**Comment by Benman2785** [comment]
ok - testet it and ofcorse it has problems xD

1. no "Umlaute" ä+ö+ü
2. wrong scaling

but so far its ok ;)

**Comment by Benman2785** [comment]
and i cant set it back to english - i need to download the "07.ini" to set it back to english ;)

**Comment by micwoj92** [comment]
You can also restart program, it will reset to default, English.

**Comment by Benman2785** [comment]
need to fix:
Language=german
to Language=deutsch

and add the new string in "NotCPUCores1.7.2.1-118-g75e7384"
"Reset to default Language" to "Standardsprache wiederherstellen"

ADDITIONAL
would be nice if the scaling errors

EDIT:
here a new version - only missing the new string ;)

[german.txt](https://github.com/rcmaehl/NotCPUCores/files/6054976/german.txt)

**Comment by micwoj92** [comment]
Reset to default is not currently translatable. You should change encoding to unicode in your editor settings and it should work. What is that scaling error you mean? Could you post screenshot?

**Comment by micwoj92** [comment]
I checked your old version and it works with Umlaut like ü for example in this screen

![image](https://user-images.githubusercontent.com/45581170/109394893-a09a0300-7929-11eb-8126-30d55701be90.png)

**Comment by Benman2785** [comment]
[german.txt](https://github.com/rcmaehl/NotCPUCores/files/6054996/german.txt)

need to save it as ANSI ;)

**Comment by Benman2785** [comment]
ps the new version is better - as there is less scaling errors ;)

**Comment by Benman2785** [comment]
![image](https://user-images.githubusercontent.com/21282980/109427621-79a80380-79f3-11eb-8f0d-36e09eb636d8.png)
here you see some scaling issues: like at "Wartungscenter"

![image](https://user-images.githubusercontent.com/21282980/109427635-8fb5c400-79f3-11eb-9faa-8fe87a526a3e.png)
here you see that "Betriebssystem" has no ":" - but in english version it says "OS:"

ps i also cant find: "Last AMD CCX" or in german "letztes AMD CCX" - but i dont know if that was removed in earlier versions

**Comment by Benman2785** [comment]
version 1
[german.txt](https://github.com/rcmaehl/NotCPUCores/files/6133172/german.txt)

version 2
[german.txt](https://github.com/rcmaehl/NotCPUCores/files/6133189/german.txt)

fixed a small error
+
and i am not happy with "Spielname" (Game Name) - added version 2 with "Name des Spiels" (Name of Game)

**Comment by Benman2785** [comment]
![image](https://user-images.githubusercontent.com/21282980/111002777-4a47ae00-8386-11eb-9444-106dbde0c90c.png)

![image](https://user-images.githubusercontent.com/21282980/111002789-516ebc00-8386-11eb-85e3-5a926985296f.png)

![image](https://user-images.githubusercontent.com/21282980/111002812-5d5a7e00-8386-11eb-9eca-fa8248e57a49.png)

![image](https://user-images.githubusercontent.com/21282980/111002840-65b2b900-8386-11eb-9e25-5ce52a362821.png)

![image](https://user-images.githubusercontent.com/21282980/111002865-6e0af400-8386-11eb-963f-b743dd015d4b.png)

here is everything with version 2 ;)

maybe i will do french or spanish too - but in both languages i am pretty rusty xD

**Comment by Benman2785** [comment]
hehe - fixed more errors (never use "replace all" for ue = ü etc)
[german.txt](https://github.com/rcmaehl/NotCPUCores/files/6133690/german.txt)


here is my first try of spanish - needs a native speaker to look over it:
[spanish.txt](https://github.com/rcmaehl/NotCPUCores/files/6133692/spanish.txt)

**Comment by micwoj92** [comment]
I think separate issue should be made for spanish

**Comment by Benman2785** [comment]
@rcmaehl 
when i use "NotCPUCores1.7.2.1-132-g1a6898f"
when i load german.ini there is an error!
instead of "physische Kerne" it says: Physical Cores

**Comment by Benman2785** [comment]
@rcmaehl 
found it:

"Physcial Cores=physische Kerne"
should be
"Physical Cores=physische Kerne"
i dont know how i did that xD
