### ISSUE TITLE
load profile with different language doesnt work correct!

### ISSUE THREAD

**Issue by Benman2785** [rcmaehl/NotCPUCores#114]
![image](https://user-images.githubusercontent.com/21282980/111299086-cfb1b380-864f-11eb-8dd2-3a8166970a11.png)
here i loaded a profile with custom core affinity
it sould say: "physische Kerne" but says custom

on streaming tab its also strange:
![image](https://user-images.githubusercontent.com/21282980/111299348-1dc6b700-8650-11eb-835c-20e8e9887cf9.png)
also looks wrong :/

**Comment by Benman2785** [comment]
when i look into the *.ncc files it is clear why that happens

you should give fixed variables for each setting (like physical cores is "x" and non physical cores are "y" etc) - then the would load correct with each language

**Comment by micwoj92** [comment]
Good catch, I haven't tested the translation systems extensively.

**Comment by rcmaehl** [comment]
I may have broken this a few releases ago trying to make the settings file look nicer. Try saving a new profile after changing languages, that profile probably works

**Comment by Benman2785** [comment]
@rcmaehl 
using a language file and then saving profile fixes this.

i would suggest you use this:
`
[Variables]
a = all cores
b = first core
c = first 2 cores
d = first 4 cores
etc...
p1 = low
p2 = below normal
p3 = normal
etc...
o1 = broadcaster cores
o2 = main process cores
o3 = remaining cores
[General]
Process=
SplitAs="f"
Threads=1,3,5,7,9,11,13,15    // I changed this to show what it actually does
Children=false
Priority= "p3"
[Streaming]
SplitAs="g"
Threads=2,4,6,8,10,12,14,16    // I changed this to show what it actually does
Software=OBS    // doesnt needs to be changed
Children=false
Priority="p4"
Assignment="o1"
`
