### ISSUE TITLE
Failed to adjust affinity

### ISSUE THREAD

**Issue by Draconixss** [rcmaehl/NotCPUCores#117]
I already run the app as administrator, but whenever i try to assign something, this log is appear

!> All Cores used for Assignment, Max Performance will be prioritized over Consistent Performance
NOTEPAD.EXE optimizing in the background until all close...
Failed to adjust affinity of csrss.exe - Access Denied (Access)
Failed to adjust affinity of wininit.exe - Access Denied (Access)
Failed to adjust affinity of csrss.exe - Access Denied (Access)
Failed to adjust affinity of services.exe - Access Denied (Access)
Failed to adjust affinity of Memory Compression - Access Denied (Access)
Failed to adjust affinity of svchost.exe - Access Denied (Access)

**Comment by hipocentrum** [comment]
Not a bug
https://github.com/rcmaehl/NotCPUCores/issues/110

**Comment by rcmaehl** [comment]
As @hipocentrum noted, not a bug. I might adjust this in 1.7.3.1 by excluding these specific processes if I get too many complaints.

**Comment by Draconixss** [comment]
okay, thanks for your response
