### ISSUE TITLE
Latest version won't launch "Autolt Error - Error: Array variable [...]"

### ISSUE THREAD

**Issue by Stuffz43** [rcmaehl/NotCPUCores#120]
I've never written one of these GitHub issues before so sorry in advance if I'm doing something wrong. 
I've been using NotCpuCores for a long time now, and everytime a new version came out I would swap the .exe for the new one without a problem, but now after swapping to 1.7.3.0 I keep getting this error window:
![NotCPUCores_2021-09-12_15-05-25](https://user-images.githubusercontent.com/61602138/132990717-ef89c257-73dc-429a-9fc0-a22e51e4f2f0.png)

NotCPUCores refuses to open **at all**
What's weird about this is I used v1.7.3 before about a week ago for the first (and only) time and it worked perfectly fine. It's only today that it won't work. I've tried:
- Deleting the v.1.7.3.0 .exe file, then downloading a new 64-bit & 86-bit version straight from the release page and trying them
- restarting my computer, then repeating the above step
- I'm definatley providing admin privileges

The only thing that worked was downgrading myself all the way back to v1.7.0.0 (I haven't tried to actually _use_ it yet, but it successfully launches the window unlike the newer version, so I'm assuming it works like it should). I've no idea what I've done wrong.

If it helps I'm on a Windows 10 comp, only using English and I don't think I've ever really tinkered with the settings of the app

**Comment by rcmaehl** [comment]
I'll investigate this issue. Give me some time

**Comment by rcmaehl** [comment]
It looks like this may be an issue with Steam Libraries. One moment

**Comment by ronoverdrive** [comment]
Can confirm this is related to Steam. Had this same error back with the previous Steam Beta rolling back fixed it until the latest update.

**Comment by rcmaehl** [comment]
This is what I get for trusting other programmers

**Comment by Stuffz43** [comment]
> Can confirm this is related to Steam. Had this same error back with the previous Steam Beta rolling back fixed it until the latest update.

I'm afraid I'm not on any beta and I seem to be on the latest version of Steam, what now? ;(

**Comment by rcmaehl** [comment]
I'll be releasing a patch by the end of the day

**Comment by Stuffz43** [comment]
Oh that's perfect, thank you!

**Comment by Stuffz43** [comment]
It works! Thank You!
