### ISSUE TITLE
Create installer with NSIS

### ISSUE THREAD

**Issue by rcmaehl** [rcmaehl/NotCPUCores#13]
Create installer with NSIS

**Comment by AnonymerNiklasistanonym** [comment]
If you do want to start with the `.nsi` script for the installer from scratch but from a simple and commented working example template I can recommend you my own repository where I not long ago experimented *(not professionally!)* with NSIS (The whole repository are just templates and everything is MIT).

Just switch the names/links/pictures to your own (or remove installer pages/functions, icons and pictures completely - as you like) and you should be ready to go with this `.nsi` script.

* [Repository Link](https://github.com/AnonymerNiklasistanonym/NsiWindowsInstallerExamples)
* [Link to the template `.nsi` script of a "modern UI" example](https://github.com/AnonymerNiklasistanonym/NsiWindowsInstallerExamples/blob/master/example_03_modern_ui_(recommended)/ExampleProgramModernUI.nsi)

If you already know *how to NSIS* - I didn't know this. I just followed this repository, saw the issue and thought the template could help you accomplishing a simple but working installer :)

**Comment by rcmaehl** [comment]
@AnonymerNiklasistanonym Thanks for the info! I'll look into it when I can :)
