### ISSUE TITLE
Multiple different versions of same language necessary?

### ISSUE THREAD

**Issue by VoodaGod** [rcmaehl/NotCPUCores#19]
i'll be happy to do the German translation, but is it necessary to have a seperate file for each variety of German if they will be identical?

**Comment by rcmaehl** [comment]
I single file for German can be used. It'd need to be named 07.ini. However, translation won't be added until 1.7 (~March 1) despite part of the files being there

**Comment by VoodaGod** [comment]
ok cool i'll get on that translation then
