### ISSUE TITLE
Include a LICENSE file

### ISSUE THREAD

**Issue by Two-Tone** [rcmaehl/NotCPUCores#2]
The README says that the project is open source, but without a license, it's still fully copyrighted to you.

I suggest a simple license, such as the [MIT License](https://en.wikipedia.org/wiki/MIT_License).

**Comment by eduardog3000** [comment]
The README says `Please do not put up for sale.`, but the license says `Permission is hereby granted...without limitation the rights to...sell copies of the Software`. You might want to choose a license that doesn't allow sale of the software.
