### ISSUE TITLE
Minimize Window

### ISSUE THREAD

**Issue by VoodaGod** [rcmaehl/NotCPUCores#28]
i've been using NotCPUCores instead of CPUCores recently, and i'd like to be able to minimize the window, maybe even to the system tray, as it does take a while to start up & would be more convenient to just start once & then optimize games when needed

**Comment by rcmaehl** [comment]
This isn't too terribly difficult. I'll see if I can have it done today.

**Comment by rcmaehl** [comment]
Added in 8ab4fedae923811400bfdabc01a3a9f28f4a3960
