### ISSUE TITLE
Steam Game Auto Detection

### ISSUE THREAD

**Issue by rcmaehl** [rcmaehl/NotCPUCores#3]
Automatically detect and provide a drop down for Steam Games

Add opinions / comments below

**Comment by azumukupoe** [comment]
GOG, Orgin, itch, and Twitch as well?

**Comment by rcmaehl** [comment]
@azumukupoe Possibly, Steam stores games pretty easily to detect, will have to look into how other service's store their game library info

**Comment by rcmaehl** [comment]
Added in bbd5bcfa32b1eb5923177ec3128dad94cb2584cd
