### ISSUE TITLE
request: auto-load profile on startup

### ISSUE THREAD

**Issue by Benman2785** [rcmaehl/NotCPUCores#31]
thank you for your work ;)

**Comment by rcmaehl** [comment]
1.7.1.0 to be released today.

**Comment by Benman2785** [comment]
not working in current release of 1.7.1.0
there it doesnt autoload a profile
there is no gui to set autoload profile

keep up the good work ;)

**Comment by rcmaehl** [comment]
Closing. Added in 1.7.2.0. Test build can be found in #testing on the discord server. https://discord.com/invite/uBnBcBx

**Comment by Benman2785** [comment]
doesnt work - or need how to!

**Comment by rcmaehl** [comment]
> doesnt work - or need how to!

Save profile as Autoload.ncc
