### ISSUE TITLE
Steam Library not loading

### ISSUE THREAD

**Issue by azumukupoe** [rcmaehl/NotCPUCores#32]
It's blank...
![image](https://user-images.githubusercontent.com/31339007/40421589-653f9c90-5ec7-11e8-8371-747d70f8a11c.png)

**Comment by rcmaehl** [comment]
Hi @azumukupoe 

A few questions...

1. Do you have Steam installed on your main hard drive or an different drive?
2. Do you have games installed on same hard drive as Steam?
3. Are you using Steam Family Sharing/Library Sharing at all? 

Regards

Robert

**Comment by azumukupoe** [comment]
1. Steam is installed on external drive.
2. Yes, games are installed on the same drive
3. Not at all

**Comment by rcmaehl** [comment]
I'll take a look here. By default it should be grabbing the proper steam library path from the registry, however I haven't tested external, removable drives.

**Comment by rcmaehl** [comment]
1.7.1.0 to be released today containing a way to specify steam libraries.
