### ISSUE TITLE
how do I even use this?

### ISSUE THREAD

**Issue by HS44** [rcmaehl/NotCPUCores#33]
I know I'm gonna sound stupid because it works for everyone else but I can't see an exe file, how do I use this? Help!

**Comment by rcmaehl** [comment]
Hi @HS44,

The .exe downloads for this file are located here: https://github.com/rcmaehl/NotCPUCores/releases

Additionally we're available on various software sites such as MajorGeeks and Softpedia.

Regards

Robert
