### ISSUE TITLE
Way how notcpucores work

### ISSUE THREAD

**Issue by chipoden** [rcmaehl/NotCPUCores#37]
Hello
I found your project really good and as I'm learning how to code I decided to make my version.
The problem is that AutoIt is a little hard and I'm more confortable with c#.

I wanted to know which windows services does the software close and how does It choose which processes are optimized.

I didn't find any way to send you a message so I did It here
thanks

**Comment by rcmaehl** [comment]
> I wanted to know which windows services does the software close and how does It choose which processes are optimized.

Services such as printing (aka spooler) which are not needed during gameplay are temporarily disabled while NotCPUCores runs.  I had planned to expand this however significant life events have occured this year that restrict me being able to develop NCC as much as I used to. I'd eventually like to make a freely available database of Services to help with this optimization.

For processes, only the selected process and streaming service (if selected) would be allowed to have full system resources (process affinity). All others would be restricted off of the selected cores. Plans for selecting a large number of unrestricted processes, however as previously mentioned, I don't have the free time I used to.

**Comment by chipoden** [comment]
Get It.
Did you add as exception all of windows services?
I'm testing with only 10 exceptions and It seems to work fine. Do you think it will cause any harm do the fps and do worse ?

**Comment by rcmaehl** [comment]
Currently the only system service not excluded was wuauserv (Windows Update) as it is a resource hog while running tying up RAM, CPU, and disk resources. It would probably be safe to not exclude some additional system services such as:

* WSearch (manual file searching)
* VSS (disk backups)
* PCAsrv (compability assistant for older programs)
* Defragsvc (Disk cleanup)
* ClickToRunSvc (Microsoft office)

As services to stop during gaming. If you do start including services, it is a good idea to store if they were running to begin with to prevent starting services that weren't running before. Regardless, remember to always start services you stopped as services such as they may not be needed in gaming but they may be needed afterwards.
