### ISSUE TITLE
TF2 not optimizing properly

### ISSUE THREAD

**Issue by TheRealestLad** [rcmaehl/NotCPUCores#39]
For TF2 I do not have any custom commands or launch options that alter with the cpu core useage (I have set "-high" in the command) But when I try to use NotCPUCores to limit tf2 to use only the physical cores (0 and 2) it is very likely it won't save or will randomly reset back to using all the cores (2 physical cores and 2 virtual cores).

So how do I know this? I use Task Manager to see if TF2 is running on the cores I want it to run on; sometimes when the optimization actually works: in TM, TF2, Details, right click hl2.exe (it is TF2), and go on the set affinity it shows that only cores 0 and 2 are running/used. When the cpucores app doesn't work TM says that TF2 is using all the cores.

**Comment by rcmaehl** [comment]
What TF2 launch options are you using. I can load it up later on today and take a look to see if Steam or the engine are doing anything funky.

**Comment by TheRealestLad** [comment]
> 
> 
> What TF2 launch options are you using. I can load it up later on today and take a look to see if Steam or the engine are doing anything funky.

My launch options are '-high -novid -windowed -noborder -cl_crosshair_scale 0'

**Comment by rcmaehl** [comment]
> > What TF2 launch options are you using. I can load it up later on today and take a look to see if Steam or the engine are doing anything funky.
> 
> My launch options are '-high -novid -windowed -noborder -cl_crosshair_scale 0' Also pleas refer/read my other similar post about the steam.exe process instead of coming here.

Assuming you're on a 64-bit PC, please try out 1.7.1.0-beta and let me know if that fixes your issue

**Comment by TheRealestLad** [comment]
> 
> 
> > > What TF2 launch options are you using. I can load it up later on today and take a look to see if Steam or the engine are doing anything funky.
> > 
> > 
> > My launch options are '-high -novid -windowed -noborder -cl_crosshair_scale 0' Also pleas refer/read my other similar post about the steam.exe process instead of coming here.
> 
> Assuming you're on a 64-bit PC, please try out 1.7.1.0-beta and let me know if that fixes your issue

Sorry I was late I'll try asap

**Comment by rcmaehl** [comment]
> 
> Sorry I was late I'll try asap
> 
> NEW EDIT: For some reason my laptop seems to be only using the physical cores now after I did driver updates; checking affinity of any program in task manager only shows cores 0-1, nothing else; before it'd show 4 cores (2 physical and 2 fake cores). So I cannot really confirm.

Likely a Zombieload patch delivered by your manufacturer. I appreciate trying though!

**Comment by TheRealestLad** [comment]
> 
> 
> > Sorry I was late I'll try asap
> > NEW EDIT: For some reason my laptop seems to be only using the physical cores now after I did driver updates; checking affinity of any program in task manager only shows cores 0-1, nothing else; before it'd show 4 cores (2 physical and 2 fake cores). So I cannot really confirm.
> 
> Likely a Zombieload patch delivered by your manufacturer. I appreciate trying though!

**Comment by TheRealestLad** [comment]
I tried using the app on another computer to test on tf2 and the app actually works even after closing. Sorry for the long wait.
