### ISSUE TITLE
Add Option to call Windows' own clean up utilities

### ISSUE THREAD

**Issue by rcmaehl** [rcmaehl/NotCPUCores#4]
Add Option For Defrag
Add Option For Trim SSDs
 
Add opinions / comments below

**Comment by preyator** [comment]
It will be wasted work. There are other free specialized software which do it well. Yeah, defrag does help with loading screens.

**Comment by rcmaehl** [comment]
Hi preyator,

Thanks for the feedback, I will be including a recommended free software list soon.

**Comment by rcmaehl** [comment]
Added
