### ISSUE TITLE
Looks like an add company pelted the package here.

### ISSUE THREAD

**Issue by cavedoggy** [rcmaehl/NotCPUCores#42]
https://www.hybrid-analysis.com/sample/d9b9167a3153b4dcf9b6537c52d7f300c53108027e3166d29e3aca17e0504ef1

http://tinyurl.com/y5cwncdg

maybe delete and reupload or notify the GitHub IT guys

**Comment by rcmaehl** [comment]
Crowdstrike is an enterprise endpoint protection software. I've been aware of their false positive for a while and don't consider it a priority as enterprise users are highly unlikely to be using this software. If you are playing games at work and using this software and this is causing an issue, let me know and I'll reach out to them, but until then I haven't consider them an issue.

**Comment by rcmaehl** [comment]
Ah, I see the issue. Looks like a trojan by Zpevdo has similarities in one way or other. I may release an minor update just to decrease false positives. Hopefully this shouldn't require too much of a rework

**Comment by rcmaehl** [comment]
I have released a new version. There should be no source code changes as I've compiled it from the 1.7.0.0 source as included in the 1.7.0.0 release. The only real changes are file metadata and debug strings still being included. VirusTotal shows only 1 false positive now so this should be resolved. Please let me know again if any issues occur with notable false positives!
