### ISSUE TITLE
Assignment Ranges not functioning properly

### ISSUE THREAD

**Issue by evilmtv** [rcmaehl/NotCPUCores#43]
I have a 8C16T CPU and I intend to do:
6 threads for the game
2 threads for everything else
8 threads for OBS encoding

When I do these settings:
Work/Play: `Custom, 1-6`
Stream: `Last Half`
Assign Other Processes: `Remaining Cores`
![image](https://user-images.githubusercontent.com/19277738/57018681-fe3e6500-6c56-11e9-9936-2669f67e69d5.png)
Everything works fine, game is assigned first 6 cores and OBS is assigned last 8 cores.

However, if I choose to do this instead which should mean the same thing:
Work/Play: `Custom, 1-6`
Stream: `Custom, 9-16`
Assign Other Processes: `Remaining Cores`

Other processes:
![image](https://user-images.githubusercontent.com/19277738/57018748-2928b900-6c57-11e9-9c1f-239c89f26d5f.png) ![image](https://user-images.githubusercontent.com/19277738/57018753-2d54d680-6c57-11e9-9978-379d8e46aad4.png)
Game:
![image](https://user-images.githubusercontent.com/19277738/57018765-334ab780-6c57-11e9-99b6-234c4505563c.png)
OBS:
![image](https://user-images.githubusercontent.com/19277738/57018774-39409880-6c57-11e9-881e-d14770c01029.png)

**Comment by rcmaehl** [comment]
I'll try to get this added this weekend. Should be a simple enough fix to ignore anything that already has a custom allocation.

**Comment by evilmtv** [comment]
I do not know the backend but I think it may be deeper than that. It seems that the stream process (OBS) is not even being assigned to its own cores. Perhaps it's not fully reading the user provided value i.e. just 9 instead of 9-16

**Comment by evilmtv** [comment]
On further testing, it seems its only bugged for Stream process if i use the dash `-`. Comma `,` works fine.

**Comment by rcmaehl** [comment]
> On further testing, it seems its only bugged for Stream process if i use the dash `-`. Comma `,` works fine.

I'll take a look in to this.
