### ISSUE TITLE
Allow for multiple Work/Play processes

### ISSUE THREAD

**Issue by evilmtv** [rcmaehl/NotCPUCores#44]
**Minor issue, probably uncommon.**

It's a problem for games launched with the Origin Client (at least Apex Legends that I know of).
The game's process `r5apex.exe` is protected and can't have its affinity or process priority changed once it is started up.
![image](https://user-images.githubusercontent.com/19277738/57019092-0519a780-6c58-11e9-9df9-2b059360fded.png)

Unique traits:
- The game inherits `Origin.exe` affinity settings by default
- NotCPUCores is able to catch and adjust `r5apex.exe` affinity settings (when considered as 'Other Processes') if it is running before game is launched.

Problem:
- NotCPUCores can't begin unless game is already running (or it'll auto stop if it detects game isn't running, I'm not too sure about the backend)

The current tedious workaround:
1. Manually assign 'Origin.exe`'s affinity with `Task Manager`
2. Launch game so `r5apex.exe` is fixed with the affinity settings I've assigned earlier
3. Run NotCPUCores 

As I've mentioned, it is application specific and probably an issue affecting only a small number of your program's userbase, but it may still be useful for others.

**Comment by rcmaehl** [comment]
This isn't that common but is becoming more common. The option to optimize child processes as well should resolve this issue. Planning to release an update here mid summer.
