### ISSUE TITLE
Hotkey conflict problem

### ISSUE THREAD

**Issue by ctsgzs** [rcmaehl/NotCPUCores#45]
sry,my english is poor.
i found that notcpucores register the hotkey F5.
F5 is used by many games or softwares,this conflict made lots of problem.
can i suggest to fix it?

**Comment by rcmaehl** [comment]
I'll try to release an update for this this weekend along with #43 as they're simple fixes.

**Comment by rcmaehl** [comment]
Update should be released shortly!
