### ISSUE TITLE
Valve anticheat or VAC , is it safe to use with games using this anti-cheat?

### ISSUE THREAD

**Issue by OneSlize** [rcmaehl/NotCPUCores#52]
Hello, so i'd love to know if there is anyway this touches the files in game folders or somehow hooks onto processes related to steam? Thank you

**Comment by rcmaehl** [comment]
@OneSlize No, this application does not hook into steam games or processes in unapproved way that would cause issues with VAC. We currently use the URI to control Steam. You can find documentation here:

https://developer.valvesoftware.com/wiki/Steam_browser_protocol
