### ISSUE TITLE
will there be more updates?

### ISSUE THREAD

**Issue by Benman2785** [rcmaehl/NotCPUCores#53]
hey - long time nothing happend - will there be more updates anytime?

**Comment by rcmaehl** [comment]
Yes, development is on the backburner. If there's any bugs or issues you're experiencing, please let me know.

**Comment by rcmaehl** [comment]
I've added a discord for test builds and other NotCPUCores discussion. For anyone viewing this pinned issue, feel free to join it:

https://discord.com/invite/uBnBcBx
