### ISSUE TITLE
ONLY working with "All Cores" setting since 1.7.0.0 (on 2 Ryzen CPU/APU)

### ISSUE THREAD

**Issue by Benman2785** [rcmaehl/NotCPUCores#54]
Hi,
i have AMD Ryzen 5 2600X (6C/12T) and AMD Ryzen 5 2400U (4C/8T).
both Windows 10 1909 (Build 18363.592)
both 16GB DualChannel RAM (DDR4-3200CL16 and DDR4-2400CL16)

Any custom cores setting (like: 1,3,5,7,9,11) (for AMD Ryzen 5 2600X) or "Physical Cores" doesnt work! Actually non setting other than "All-Cores" work! (and this only once)
Does not work on BOTH CPUs/APUs (i can also check on Ryzen 5 2400G if you want)

debug error:
"Exited. Restoring Previous State...
Done"
...and nothing happens!

I want NotCPUCores to run games with "above normal" prio and on "Physical Cores" only - while running OBS on cores (2,4) on 2500U or (2,4,6,8) on 2600X when i stream games! (using my APU for OBS AMF Encoder // while using x264 on 2600X)

With v1.6.2.0 it works fine!

**Comment by rcmaehl** [comment]
> Any custom cores setting (like: 1,3,5,7,9,11) (for AMD Ryzen 5 2600X) or "Physical Cores" doesnt work!

Please try version 1.7.1.0. There was an issue with how some custom ranges were handled that has since been patched

**Comment by Benman2785** [comment]
not working in 17.1.0

**Comment by Benman2785** [comment]
working in 1.7.1.0 release
thank you ;)
