### ISSUE TITLE
Improve Debug Output

### ISSUE THREAD

**Issue by Benman2785** [rcmaehl/NotCPUCores#55]
hey, when i run "Debug Console" to see if NotCPUCores works fine it doesnt scroll to the newest event

would be nice if you fix that. ;)

**Comment by rcmaehl** [comment]
TODO:

Try
```
#include <GuiScrollBars.au3>

_GUIScrollBars_SetScrollInfoPos($hWnd, $SB_VERT, _GUIScrollBars_GetScrollInfoMax($hWnd, $SB_VERT))
```

**Comment by Benman2785** [comment]
sry - i dont know how to built it :(
i also dont have any compiler here

**Comment by Benman2785** [comment]
works in 1.7.1.0

thank you ;)
