### ISSUE TITLE
"Low" and "Below Normal" is not available to choose from Process Priority even when it exist in "_Optimize" function?

### ISSUE THREAD

**Issue by Trung0246** [rcmaehl/NotCPUCores#56]
Is this expected, or is it being forgotten?
![image](https://user-images.githubusercontent.com/11626920/77888581-54c67180-7221-11ea-983d-c0743126f430.png)
Version: 1.7.1.0-beta (latest release)
CPU: Ryzen 9 x3950, OS: Windows 10 1909 18363.720

**Comment by Benman2785** [comment]
i dont see any sense in that
when assigning process to specific cores and all other processes to the remaining cores there is no need for "below normal" or "low" prio - or do i miss something?

**Comment by rcmaehl** [comment]
> i dont see any sense in that
> when assigning process to specific cores and all other processes to the remaining cores there is no need for "below normal" or "low" prio - or do i miss something?

You're not wrong, but it wouldn't be too hard to implement. I've assigned it to the 2.0 Milestone which will be a full code rewrite.
