### ISSUE TITLE
ui suggestion metroui

### ISSUE THREAD

**Issue by wazerstar** [rcmaehl/NotCPUCores#6]
May I suggest something like.... 

https://www.autoitscript.com/forum/files/file/365-metrogui-udf/

Easy to work with and works well

**Comment by rcmaehl** [comment]
I'll most likely use this as I've been looking to make NCC look nicer.

**Comment by rcmaehl** [comment]
Added UDF in latest commit 5db0d80e19c4f0e0ae3f02f9a53c41a769aa026f
