### ISSUE TITLE
Fix 32-bit integer limitations for process assignments

### ISSUE THREAD

**Issue by evilmtv** [rcmaehl/NotCPUCores#67]
Running on latest x64 release https://github.com/rcmaehl/NotCPUCores/releases/tag/1.7.2.0

**Issue 1**
Game: Custom Allocation, 1-12
Broadcast Software: Custom Allocation, 17-32 OR Last Half
Assign Other Processes: Remaining Cores
This leaves 13-16 unallocated but starting throws the error:
```.....EXE optimizing in the background until all close...
Exiting Optimizations via Interrupt...Exited. Restoring Previous State...
Done
```

**Issue 2** 
"Last AMD CCX" assigns 17, 19, 21...31 instead of 17-32

**Comment by rcmaehl** [comment]
> **Issue 1**
> Game: Custom Allocation, 1-12
> Broadcast Software: Custom Allocation, 17-32 OR Last Half
> Assign Other Processes: Remaining Cores
> This leaves 13-16 unallocated but starting throws the error:
> 
> ```
> Exiting Optimizations via Interrupt...Exited. Restoring Previous State...
> Done
> ```

Currently looking into this one,

> **Issue 2**
> "Last AMD CCX" assigns 17, 19, 21...31 instead of 17-32

Fixed in 895ce6d

Will have a test build sometime soon

**Comment by evilmtv** [comment]
Awesome, I'll try to test whatever I can when its released!

**Comment by rcmaehl** [comment]
@evilmtv

The test build containing both fixes is available here: https://cdn.discordapp.com/attachments/729207579447918643/756595906912190644/9.18.B1-NotCPUCores.zip

I will be releasing it to the

**Comment by evilmtv** [comment]
Hey, didn't check github notifications hence the late reply.
Downloaded and tried the latest release:
https://github.com/rcmaehl/NotCPUCores/releases/tag/1.7.2.1

Can't even run normally now:

![image](https://user-images.githubusercontent.com/19277738/94071071-e1936600-fe25-11ea-8e8d-0b28f722ade1.png)
![image](https://user-images.githubusercontent.com/19277738/94071080-e48e5680-fe25-11ea-9650-497c050d92a0.png)

Shows me that error and the app 'freezes'. Buttons have the click animations but nothing happens

**Comment by rcmaehl** [comment]
Odd. Give me a bit to sort it out.

**Comment by evilmtv** [comment]
Tried a few combinations and all ends up that way, entirely different issue now.

1. Start app
2. Default Settings (different settings didn't work too)
3. Set game and OBS
4. Assign
5. Throws that error
6. App goes into locked-ish state

**Comment by evilmtv** [comment]
Sorry, adding on.
Restarted my PC without any other background apps just in case.
However i realize the issue only occurs when I set OBS in the `Stream` tab.

**Comment by rcmaehl** [comment]
Will have a test build fixing the locked state tonight. Small oversight on my part.

For the actual error causing the locked state, I'm looking into that now.

**Comment by rcmaehl** [comment]
I've fixed the locked state and added error codes for that specific error in this 1.7.2.2. Still doesn't fix the assignment error but doesn't lock up the program. let me know what error code you get now.

https://cdn.discordapp.com/attachments/729207579447918643/758457549056901140/9.23.B1-NotCPUCores.zip

**Comment by evilmtv** [comment]
# Only game
## Everything else OK
![image](https://user-images.githubusercontent.com/19277738/94141193-f95b0080-fe9e-11ea-9911-0ad0d5865027.png)


## All cores (and custom selecting all) NOT OK
![image](https://user-images.githubusercontent.com/19277738/94141219-00820e80-fe9f-11ea-996c-7ab5b7ef5b1a.png)
Selecting all minus one thread works:
![image](https://user-images.githubusercontent.com/19277738/94145797-aa649980-fea5-11ea-932c-e6e1711db1cf.png)


## Non-Physical Cores NOT OK
![image](https://user-images.githubusercontent.com/19277738/94141588-89994580-fe9f-11ea-9e13-3c99d5ef9e02.png)


## First AMD CCX NOT OK, different error
Does not correctly assign affinity too
![image](https://user-images.githubusercontent.com/19277738/94141663-ae8db880-fe9f-11ea-83c9-d6827d7a2067.png)
![image](https://user-images.githubusercontent.com/19277738/94141671-b2213f80-fe9f-11ea-9e06-45a9edb50fe8.png)


# With OBS
## `Remaining Cores` causes error no matter the combination
![image](https://user-images.githubusercontent.com/19277738/94145973-e39d0980-fea5-11ea-9362-8df381caee8e.png)


## Last AMD CCX OK! For OBS
![image](https://user-images.githubusercontent.com/19277738/94146295-4e4e4500-fea6-11ea-8d35-cda350edd0a9.png)
![image](https://user-images.githubusercontent.com/19277738/94146304-51e1cc00-fea6-11ea-99ea-bdad51e68197.png)


## Everything else works as expected
![image](https://user-images.githubusercontent.com/19277738/94146108-0af3d680-fea6-11ea-83a4-c3bbe266b5d0.png)
![image](https://user-images.githubusercontent.com/19277738/94146191-29f26880-fea6-11ea-9f65-9b63653d667b.png)

**Comment by rcmaehl** [comment]
Believe I've found the issue. Apparently a function I'm using to calculate process assignment is limited to 32-bits and anything over 31 cores is past the 32-bit integer limit. Will attempt to develop a patch here in a bit.

**Comment by rcmaehl** [comment]
Hi @evilmtv 

Let me know if this test build resolves your issues:
https://discordapp.com/channels/728710400367001650/729207579447918643/761803480725717003

**Comment by evilmtv** [comment]
@rcmaehl 
Link doesn't work!

**Comment by rcmaehl** [comment]
> @rcmaehl
> Link doesn't work!

Try this one:
https://cdn.discordapp.com/attachments/729207579447918643/761803480155160606/10.2.B1-NotCPUCores.zip

**Comment by evilmtv** [comment]
**Only game:**
All cores OK
**Custom:**
2-30 => CPU 0 and CPU 30 OFF. NOT OK
Expected, CPU 0, CPU30, CPU 31 OFF
2-3 => CPU 1, CPU2, CPU 31 ON. NOT OK
Expected, CPU 31 OFF too.
**First AMD CCX:**
First half threads ON but CPU 31 ON too. NOT OK

Seems to have an issue with the last thread.

**Comment by rcmaehl** [comment]
Github being overly eager to close this issue.

**Comment by evilmtv** [comment]
Let me know if you need further testing

**Comment by rcmaehl** [comment]
Hi @evilmtv 

Please try the following build:

https://github.com/rcmaehl/NotCPUCores/suites/1741211744/artifacts/33046835

**Comment by evilmtv** [comment]
Hi @rcmaehl , the 3 'not OK' cases are working as expected now.
