### ISSUE TITLE
Feature request/CI: add version to package compiled by CI

### ISSUE THREAD

**Issue by micwoj92** [rcmaehl/NotCPUCores#79]
I think lazy way to do it would be setting variable using `git describe --long --tags` and then passing it to upload file name.
for example now it would show 1.7.2.1-27-g47251d9, the problem is that currently CI uses `--depth 1` option so it does not work.  Full repo is only 1.56 MB download as of now, so I think that full history can be downloaded.

**Comment by rcmaehl** [comment]
![](https://media1.tenor.com/images/9f597a384826bce24344bd6f1b2b7dbd/tenor.gif)

**Comment by rcmaehl** [comment]
I'm off to bed. Feel free to test it out. I'll try implementing it myself tomorrow.
