### ISSUE TITLE
bug/windows 8.1: Can't launch 

### ISSUE THREAD

**Issue by micwoj92** [rcmaehl/NotCPUCores#83]
After commit https://github.com/rcmaehl/NotCPUCores/commit/cd07fd49a4520d03c4c5ad4209b21a3d98f62d36
Can't launch, tried both from CI and manually built.  Manually build on previous commit, works fine.

Error message: 

Line 24324 (File "C:\Users\johns\Desktop\NotCPUCores1.7.2.1-35-gcd07fd4.exe"):

Error: Cannot make existing variables static.

**Comment by rcmaehl** [comment]
Fixed in 0835c29
