### ISSUE TITLE
Not sure what happen

### ISSUE THREAD

**Issue by vintendpower** [rcmaehl/NotCPUCores#85]
Just restored my windows pc past few days and was looking to tweak. A little.  Used your program and not sure what happen but now my pc is very very slow even after restoring to before using notcpucore.  Please help

**Comment by rcmaehl** [comment]
Did you mess with HPET or HAGS tools at all?

**Comment by vintendpower** [comment]
Now that I think of it I did hit that hpet button. Please help thank you I don’t want to lose everything.

**Comment by vintendpower** [comment]
> Did you mess with HPET or HAGS tools at all?

Yes I hit HPET button

**Comment by rcmaehl** [comment]
I'll be adding back the warning for that button. Open command prompt as administrator and run

`bcdedit /deletevalue useplatformclock`

**Comment by rcmaehl** [comment]
Oh, and then restart
