### ISSUE TITLE
Unzip Autoit files rather than installing

### ISSUE THREAD

**Issue by micwoj92** [rcmaehl/NotCPUCores#93]
As discussed in Discord chat previously. Could drastically speed up current CI as installing takes 50% of time. 
But before doing something I will make some tests soon and post results here with installing vs unzipping to see if its really worth it.

**Comment by micwoj92** [comment]
so I did 2 tests, one was to (download+run) 10 times and the other was to download once and then run/unzip 10 times. In both tests unzipping was slower

![image](https://user-images.githubusercontent.com/45581170/107118620-5372c600-6882-11eb-8ad0-876ad60158bc.png)

![image](https://user-images.githubusercontent.com/45581170/107118635-66859600-6882-11eb-8533-e4d5662c7bd8.png)

**Comment by rcmaehl** [comment]
Installing was determined to be quicker. CBA to host a higher performance zip file.
