### ISSUE TITLE
Action Center shows no icon on Windows Vista

### ISSUE THREAD

**Issue by micwoj92** [rcmaehl/NotCPUCores#99]
![image](https://user-images.githubusercontent.com/45581170/107916413-8c87f600-6f66-11eb-9c93-0ea869751261.png)

This happens both in version 1.7.2.1 and on master branch as of commit https://github.com/rcmaehl/NotCPUCores/commit/2d7329bead6ad3d020f198fb0d414c0a2f1fc266

**Comment by rcmaehl** [comment]
I'll send you an executable on discord. I'll need you to let me know which icons do show up.

**Comment by micwoj92** [comment]
[enumicons.zip](https://github.com/rcmaehl/NotCPUCores/files/5991408/enumicons.zip)

**Comment by micwoj92** [comment]
![image](https://user-images.githubusercontent.com/45581170/108118088-21413f80-709e-11eb-9eb1-e54962facf6d.png)

works now
